//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_Lesson8B.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Department
    {
        public Department()
        {
            this.Courses = new HashSet<Course>();
        }

        
        public int DepartmentID { get; set; }
        [Display(Name = "Department")]
        public string Name { get; set; }
        public decimal Budget { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
